version: "3.4"
services:
  node:
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: 1.2.0
    image: "node.mysterium.dnp.dappnode.eth:0.1.0"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - EXTRA_OPTS=""
    volumes:
      - "myst-data:/var/lib/mysterium-node"
    ports:
      - "1294:1294/udp"
      - "59850-60000:59850-60000/udp"
volumes:
  myst-data: {}
